### ISSUE TITLE
D4.9: In-place computation in active documents (context/computation)

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#97]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** Jacobs University Bremen
- **Due:** 2017-02-28 (month 18)
- **Nature:** Demonstrator
- **Task:** T4.6 (#74): Structured documents
- **Proposal:** [p. 48](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.9/report-final.pdf)**

One of the most prominent features of a virtual research environment (VRE) is a unified user interface (UI). There are two complementary approaches that can serve as a basis for OpenDreamKit's mathematical VRE UI: computational notebooks and active structured documents. The former allows for mathematical text around the computation cells of a real-eval-print loop of a mathematical computational system and the latter makes semantically annotated documents active.

In D4.2 “Active/Structured Documents Requirements and existing Solutions” (#91) we reported on two systems in the OpenDreamKit project which follow respectively those two approaches: [Jupyter](http://jupyter.org) -- a notebook server for various computational systems -- and [MathHub.info](http://MathHub.info) -- a platform for active mathematical documents. We identified commonalities and differences and developed a vision for integrating their functionalities.

As a first step into this direction we explore in this deliverable the requirements of integrating in-situ (i.e. in-document) computation – a forte and indeed the raison-d'être of notebooks – into conventional, narrative-structured mathematical documents. We present, analyze, and classify examples for in-situ computation and explore -- in particular in a [MathHub.info](http://MathHub.info) based prototype -- how the active documents technology has to be extended to accommodate this functionality as a semantic service.

**Comment by bpilorget** [comment]
@minrk (WP leader), and I see @kohlhase was assigned?
This deliverable is due for February 2017

**Comment by minrk** [comment]
@kohlhase what needs to be done to finish this deliverable for February?

**Comment by kohlhase** [comment]
(begin internal note) 
Originally, we wanted to base this on jupyther interaction, but I think that this is probably unrealistic. I guess what we should do is to use the SCSCP connection to GAP and embed that into the generated documents. 
(end internal)
 @tkw1536

**Comment by nthiery** [comment]
Dear M18 deliverable leaders,

Just a reminder that reports are due for mid-february, to buy us some time for proofreading, feedback, and final submission before February 28th. See our [README](https://github.com/OpenDreamKit/OpenDreamKit/#submitting-a-deliverable) for details on the process.

In practice, I'll be offline February 12-19, and the week right after will be pretty busy. Therefore, it would be helpful if a first draft could be available sometime this week, so that I can have a head start reviewing it.

Thanks in advance!

**Comment by kohlhase** [comment]
I am just seeing that this is called D4.9 in the title, but in the proposal, it is D4.8. It seems that there are more such errors in the titles. 
Should we (manually) correct the titles?

**Comment by kohlhase** [comment]
I just want to point out that there is already a draft in the repository WP4/D4.8, it is not complete yet, but gives you a hint of where it is heading.

**Comment by nthiery** [comment]
On Mon, Feb 06, 2017 at 09:54:46AM -0800, Michael Kohlhase wrote:
>    I am just seeing that this is called D4.9 in the title, but in the
>    proposal, it is D4.8. It seems that there are more such errors in the
>    titles.
>    Should we (manually) correct the titles?

@bpilorget: Do you mind cross-checking this with the deliverable list
on the EU website? That's what we have to be consistent with, and then
we should fix either our file or github. Thanks!

**Comment by nthiery** [comment]
On Mon, Feb 06, 2017 at 09:55:25AM -0800, Michael Kohlhase wrote:
>    I just want to point out that there is already a draft in the
>    repository WP4/D4.8, it is not complete yet, but gives you a hint of
>    where it is heading.

Good. I'll have a look!

**Comment by kohlhase** [comment]
This is also important for the naming of the subdirectories of the **WP?** directories in the repository, they should be consistent with the grant agreement as well.

**Comment by kohlhase** [comment]
In this case I am using D4.8 since that is is in the proposal.

**Comment by bpilorget** [comment]
@nthiery and @kohlhase After having checked the EU participant portal, the names of D4.8 and D4.9 an the right ones on github so no need to change anything here.
![capture](https://cloud.githubusercontent.com/assets/14076235/22684480/d61b3442-ed1c-11e6-9848-32d68e5ebc13.JPG)

**Comment by bpilorget** [comment]
And in the Proposal I have file UserInterfaces.tex, the two deliverables being discussed refer to the right issue. And I also checked the official Proposal on the EU website, and the signed version after the 1st amendment shows that the github issues are right. But I noticed that in draft versions of the proposal for the 1st amendment the 2 deliverables names were confused.

I pushed the latest Description of the action pdf document so that you can see it.

Best

**Comment by kohlhase** [comment]
I have seen the rename (got me a bit of a hard merge from my fork). BUT the proposal on ODK.org still shows me the 4.8. Should we not update that?

**Comment by bpilorget** [comment]
Sorry for the not so smooth merge... Yes, we'll update the proposal. Maybe the rename was a human mistake at some point but now what counts is the official document.

**Comment by kohlhase** [comment]
all is fine as long as we resolve the inconsistency before it really bites us.

**Comment by nthiery** [comment]
Hi,
I am missing the calbf style file and docicon tikzlibrary to compile the report. Is this part of a typical texlive distribution (I believe I have texlive-all here)? Or should they be added to the repo?

Cheers,
                           Nicolas

**Comment by kohlhase** [comment]
sorry, I had already added them on the KWARC fork, but had not pushed. Now they should be there. 
the styles are not "official", calbf is just a convenience macros set; docicon might be useful for anyone who uses tikz (it provies a document icond node).

**Comment by kohlhase** [comment]
BTW, the report and implementation are on track, @tkw1536 is working on that as we speak.

**Comment by nthiery** [comment]
>    sorry, I had already added them on the KWARC fork, but had not pushed.
>    Now they should be there.
>    the styles are not "official", calbf is just a convenience macros set;
>    docicon might be useful for anyone who uses tikz (it provies a document
>    icond node).

Ok, thanks for the quick feedback!

**Comment by kohlhase** [comment]
> Yes, we'll update the proposal.

@nthiery @bpilorget I think we should do that very soon, since the generated titles are wrong otherwise.

**Comment by bpilorget** [comment]
As far as I understand the proposal files, the generated titles are right. What I need to update is the Grant Agreement PDF version on the website.

**Comment by kohlhase** [comment]
no, that is not true, the reports have the line
```
\deliverable{UI}{adcomp}
```
 which reads ```proposal.pdata``` and in this case, this contains that the deliverable ```UI:adcomp``` is D4.8, hence the wrong title of my report :-(

**Comment by kohlhase** [comment]
and I suspect that this is true for other deliverables as well (i.e at least all D4.y, where y>=9).

**Comment by bpilorget** [comment]
I right now don't know how to modify (nor open) the proposal.pdata document. 
If you know, please have a go. I need to update my tools next week with Erik. I currently cannot create a pdf document from the latex files. So this will have to wait Monday or Tuesday.

**Comment by kohlhase** [comment]
I think that @nthiery or I should have a look at this.

**Comment by nthiery** [comment]
>    I think that [1]@nthiery or I should have a look at this.

I was offline for the day for a seminar. I'll work on this tomorrow
morning, unless you are quicker :-)

Cheers,
                                        Nicolas

**Comment by kohlhase** [comment]
> unless you are quicker :-)

not likely, I have my last course tomorrow, and it is not prepared yet. Sorry.

**Comment by nthiery** [comment]
Hi @kohlhase,
I am recompiling the proposal. I just fixed one typo in the style file which caused trac issue numbers not be included in the pdata (7ace63c0fee5f2d7c94b2bd51704d2a961510b8f), and a trivial one in a bib file of yours (4a270f9cc24072efdded1b210eed85db7393a893).

There remains one issue that you would be quicker to track and fix: after a `make final` on my machine, the task titles currently do not appear in final.pdf! See e.g. T1.1 p. 44.

This ends up changing the page numbering, so I did not commit the new final.pdata ...

**Comment by kohlhase** [comment]
did you push?

**Comment by nthiery** [comment]
>    did you push?

Oops. Now, yes :-)

**Comment by kohlhase** [comment]
I have fixed the titles, but unfortunately, I am still getting that the in-place computation is D4.8 there. 
I am not sure where this discrepancy may come from. Can you post the deliverables list of the EU? 
I fear that we will need to compare final.pdf  to that list manually

**Comment by kohlhase** [comment]
Ah, I think I understand what is happening. We just have to switch the deliverables D4.8 and D4.9 in the proposal source, and then things should line up again. Let me try this and see if that works.

**Comment by kohlhase** [comment]
OK, this seems to indeed solve the inconsistency.

**Comment by kohlhase** [comment]
We can go back to real work on the report now.

**Comment by kohlhase** [comment]
I have a relatively feature complete version of the report. @tkw1536 will work on the implementation some more (so that it conforms more to the specification), we will have this demoable for the review. 
The next steps are to let this rest a bit, reread, and declare victory.

**Comment by kohlhase** [comment]
> The next steps are to let this rest a bit, reread, and declare victory.

I did that, and had to do a bit more for real feature-completeness. The only work that needs to be done is in section 4, which @tkw1536 will do. 

So (as with D4.3, see #92) it would be good if Nicolas or Benoit could have a look at this deliverable and tell me if something else needs to be done before I travel.

**Comment by minrk** [comment]
Thanks, @kohlhase!

**Comment by nthiery** [comment]
Hi,

I just browsed through the report. It looks good, thanks!

I fixed some typos. Note that I allowed myself to use \delivref rather than \cite to refer to other deliverables, for consistency with what we have done in other reports.

Things that remain to do:
- Detailed proofreading; there certainly are quite a few remaining typos. @minrk maybe?
- Writing down an abstract in the github description, giving a brief overview of what the deliverable is about, how it fits in the greater ODK picture and what was achieved. Plausibly, most of the required pieces of language can be taken from the current introduction and conclusion; so that should not be too much work. @tkw1536: could you have a first shot at it?

Cheers,
                             Nicolas

**Comment by minrk** [comment]
@nthiery I'll give it a proofreading pass.

**Comment by tkw1536** [comment]
@nthiery Finalising this report is on my list for tomorrow. In section four I in particular still have to describe a demo I have been working on as well as replace some sketches with actual screenshots.

**Comment by minrk** [comment]
I did a proofreading pass, excluding section four to avoid conflicts.

**Comment by tkw1536** [comment]
@nthiery I have just pushed some work on section 4 as well as all over the report. There also is a first version of the abstract (committed separately as abstract.tex) which I have just put into the description of this issue. Content-wise the report is done from my side, but I still want to read through it once more over the weekend. Also I still have to fix a minor issue with regards to one of the linked demos.

**Comment by tkw1536** [comment]
OK, I have gone over it once more and have fixed a bunch of typos. From my side the report is now completely done and ready to be submitted with the exception of one thing: Do I include the abstract written above into the document itself? If so, how?

**Comment by nthiery** [comment]
I updated the abstract above to try to give some more context to the reviewers (please proofread/edit! you know better what this deliverable is about), and integrated into the report by running:

    rm WP4/D4.9/report.pdf WP4/D4.9/github-issue-description.*
    make WP4/D4.9/report.pdf 

Reading the report now!

**Comment by nthiery** [comment]
Two minor things, and then it's indeed good to go:
- Maybe refer to Figure 5 in 2.1? Maybe even put the picture in 2.1 to make things right away more concrete?
- For consistency with our other documents, please refer to other deliverables by using e.g.  `\delivref{UI}{mathhub-editing}` or its `\longdelivref` counterpart rather than with citations. To find the deliverable labels, I usually search through <ODK>/Proposal/final.pdata.
Thanks!

**Comment by minrk** [comment]
I updated it to use delivref where appropriate. I'll leave it to the authors to decide what to do about the Figure, if anything.

**Comment by tkw1536** [comment]
Concerning moving Figure 5, I think it is better to leave it as is. We first introduce some of the possible applications (in section 2), then describe our approach (section 3) and then only in section 4 we show what we have concretely achieved. Moving Figure 5 away from section 3 might make it more concrete in the beginning, but could also be interpreted as the screenshot showing something that already existed before.

**Comment by minrk** [comment]
@tkw1536 thanks! In that case, I think this report is ready to submit.

**Comment by nthiery** [comment]
Ok. On it!

**Comment by nthiery** [comment]
I allowed myself some tweaking of the figures and listings for better readability.

**Comment by nthiery** [comment]
Submitted!
Thanks and congratulations @tkw1536, @kohlhase for a nice deliverable and @minrk for the help!
